# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: NuGetToolInstaller@1
    inputs:
      checkLatest: true

  - task: VSBuild@1
    inputs:
      solution: Src/TodoApplication.sln
      vsVersion: latest
      configuration: Release
      clean: true
      msbuildArchitecture: x64

  - task: VSTest@2
    inputs:
      testSelector: testAssemblies
      testAssemblyVer2: Src/Todo.Tests/bin/*.Tests.dll
      vsTestVersion: latest
      codeCoverageEnabled: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: VSTest