trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - pipelines/*
      - iac/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: stage_deploy
  displayName: Production
  jobs: 
  - job: job_deploy_infrastructure
    displayName: Deploy Some Infrastructure
    steps:
    - bash: |
        echo "this is some build job"
        echo "creating a pipeline variable"
        SOMEVALUE="bleh"
        echo "##vso[task.setvariable variable=someName;isOutput=true;]$SOMEVALUE"
        echo "variable value is $(someName)"
  - job: job_deploy_code
    displayName: Deploy Some Code
    dependsOn: ['job_deploy_infrastructure']
    variables: 
      someName: $[ dependencies.job_deploy_infrastructure.outputs['someName'] ]
    steps: 
    - bash: |
        "the variable value is $(someName)"